<?php

namespace Database\Seeders;

use App\Models\Major;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MajorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Major::create([
            'logo' => 'https://smkn2sumedang.sch.id/icons/akl.svg',
            'name' => 'Akuntansi dan Keuangan Lembaga',
            'slug' => 'AKL',
            'excerpt' => 'Akuntansi adalah salah satu bidang studi yang memiliki peran penting dalam kegiatan bisnis.',
            'insight' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Apa itu jurusan Akuntansi?</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5">Jurusan akuntansi adalah belajar cara memelihara keuangan. Ini mempersiapkan siswa untuk menjadi akuntan dengan mengajar mereka tentang prinsip-prinsip akuntansi seperti audit, pelaporan, penganggaran dan peraturan pajak. Akuntansi adalah sarana yang digunakan perusahaan atau organisasi untuk menyampaikan informasi keuangannya.</p><ul class="space-y-2"></ul></div>',
            'career' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Jenjang Karir Lulusan</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5"></p><ul class="space-y-2"><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Staf Akuntansi/Keuangan Perusahaan</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Staf Perpajakan</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Kasir</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Teller</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Staf Administrasi</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Customer Service</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Wirausaha</span></li></ul></div>',
            'curriculum' => '<ol class="text-sm space-y-2"><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Ekonomi bisnis dan administrasi umum</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Akuntansi perusahaan jasa, dagang dan manufaktur</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Akuntansi lembaga/instansi pemerintah</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Akuntansi keuangan</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Komputer akuntansi</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Perpajakan</li></ol>',
        ]);
        Major::create([
            'logo' => 'https://smkn2sumedang.sch.id/icons/pplg.svg',
            'name' => 'Pengembangan Perangkat Lunak dan Gim',
            'slug' => 'PPLG',
            'excerpt' => 'Salah satu kompetensi keahlian di SMKN 2 Sumedang dalam bidang Teknologi Komputer dan Informatika.',
            'insight' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Apa itu jurusan Pengembangan Perangkat Lunak dan Gim?</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5">Pengembangan Perangkat Lunak dan Gim (PPLG) adalah salah satu kompetensi keahlian dalam bidang Teknologi Komputer dan Informatika yang secara khusus mempelajari tentang pemrograman komputer mulai dari perancangan, pembuatan, pemeliharaan dan juga proses manajemennya.</p><ul class="space-y-2"></ul></div>',
            'career' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Jenjang Karir Lulusan</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5"></p><ul class="space-y-2"><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Mampu bekerja di berbagai bidang karena sudah dibekali dengan berbagai ilmu dan pengetahuan.</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Dalam melakukan kerja lapangan akan lebih mudah karena saat pembelajaran sudah sering melakukan kerja praktek</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Pekerjaan nya yang relatif mudah dan santai, dapat dikerjakan dimanapun dan kapanpun menggunakan koneksi internet</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Lebih terdepan dari jurusan lainnya dan orang awam diluar sana karena jurusan RPL lebih mengerti dan mendalami berbagai teknologi</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Mampu memasang sebuah PC</span></li></ul></div>',
            'curriculum' => '<ol class="text-sm space-y-2"><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Basis Data</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Sistem Komputer</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pemrograman Berbasis Teks, Grafis, dan Multimedia</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pemrograman Perangkat Bergerak (mobile)</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pemrograman Web</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pemrograman Berorientasi Objek</li></ol>',
        ]);
        Major::create([
            'logo' => 'https://smkn2sumedang.sch.id/icons/mplb.svg',
            'name' => 'Manajemen Perkantoran dan Layanan Bisnis',
            'slug' => 'MPLB',
            'excerpt' => 'Kompetensi Keahlian Manajemen Perkantoran dan Layanan Bisnis mempelajari segala jenis kegiatan kantor.',
            'insight' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Apa itu jurusan Manajemen Perkantoran dan Layanan Bisnis?</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5">Manajemen Perkantoran dan Layanan Bisnis (MPLB) adalah salah satu kompetensi keahlian di SMKN 2 Sumedang yang mempelajari pengelolaan bisnis dengan fokus pada manajemen perkantoran dan manajemen logistik, kewirausahaan serta keterampilan dan sikap dalam menyelesaikan pekerjaan-pekerjaan kantor.</p><ul class="space-y-2"></ul></div>',
            'career' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Jenjang Karir Lulusan</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5"></p><ul class="space-y-2"><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Resepsionis</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Sekretaris Junior</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Staff Administrasi</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Asisten Arsiparis</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Customer Service</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Event Organizer</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Wirausaha</span></li></ul></div>',
            'curriculum' => '<ol class="text-sm space-y-2"><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Ekonomi dan bisnis</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan administrasi umum</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Komunikasi di tempat kerja</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan kearsipan</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Teknologi Perkantoran</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan rapat/pertemuan</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan keuangan sederhana</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan sumber daya manusia (SDM)</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan sarana dan prasarana</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan humas dan keprotokolan</li></ol>'
        ]);
        Major::create([
            'logo' => 'https://smkn2sumedang.sch.id/icons/pm.svg',
            'name' => 'Pemasaran',
            'slug' => 'PM',
            'excerpt' => 'Jurusan yang mempelajari seluk beluk pasar secara meluas termasuk menciptakan produk yang berkualitas.',
            'insight' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Apa itu jurusan Pemasaran?</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5">Pemasaran adalah kompetensi keahlian yang mempelajari dasar-dasar kemampuan dan keilmuan menjadi seorang maarketing, baik secara konvensional maupun melaui media daring (online/internet). Selain itu juga, mempelajari stratei pasar, kewirausahaan dan membuka peluang bisnis.</p><ul class="space-y-2"></ul></div>',
            'career' => '<div><div class="flex items-center"><div><h1 class="text-xl font-semibold">Jenjang Karir Lulusan</h1><p class="text-sm"></p></div></div><p class="text-base font-light mt-5"></p><ul class="space-y-2"><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Sosial Media Marketing</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Tenaga Pemasaran</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Pramuniaga</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Pengelola Gudang</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Kasir</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Bisnis Retail</span></li><li class="list-disc ml-4 pl-2 text-dark"><span class="text-black">Wirausaha</span></li></ul></div>',
            'curriculum' => '<ol class="text-sm space-y-2"><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Ekonomi bisnis dan administrasi umum</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Marketing</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Customer service</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Komunikasi Bisnis</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengelolaan Bisnis Retail</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Strategi marketing visual merchandising</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Pengemasan dan pendistribusian produk</li><li class="flex items-center"><img alt="pointer" loading="lazy" width="10" height="10" decoding="async" data-nimg="1" class="mr-5" src="/icons/pointer.svg" style="color: transparent;">Administrasi transaksi</li></ol>'
        ]);
    }
}
